// TrabajoPractico9/tp9Angular/tp9angular/src/app/components/detalle/detalle.component.ts
import { Component, OnInit } from "@angular/core";
import { ServicioService } from "src/app/servicios/servicio.service";
import { ActivatedRoute } from "@angular/router";

@Component({
  selector: "app-detalle",
  templateUrl: "./detalle.component.html",
  styleUrls: ["./detalle.component.css"],
})
export class DetalleComponent implements OnInit {
  instrumento: any;
  envioGratis: boolean;
  constructor(
    private activatedRoute: ActivatedRoute,
    private servicio: ServicioService
  ) {}

  ngOnInit() {
    this.activatedRoute.params.subscribe((params) => {
      this.servicio.getInstrumentosXId(params["id"]).subscribe((data) => {
        this.instrumento = data;
      });
      console.log(this.instrumento);
    });
  }
}

<div>
  <div class="card-columns">
    <div class="card">
      <img
        class="card-img-top"
        src="http://localhost:9002/imagenes/{{ instrumento.urlImagen }}"
        alt=""
      />
      <div class="card-body">
        <h4 class="card-title">{{ instrumento.instrumento }}</h4>
        <p class="card-text">
          {{ instrumento.descripcion }}
        </p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <span>{{ instrumento.cantidadVendida }} vendidos</span>
        <h2 class="card-title">${{ instrumento.precio | number: "3.2-5" }}</h2>
        <p>
          <span>Marca: {{ instrumento.marca }}</span>
          <br />
          <span>{{ instrumento.modelo }}</span>
        </p>
        <p
          style="color: green; font-size: 10pt;"
          *ngIf="instrumento.precioEnvio == 'G'; else costoEnvio"
        >
          <img src="http://localhost:9002/imagenes/camion.png" />Envío gratis a
          todo el país
        </p>

        <ng-template #costoEnvio>
          Costo de Envío:<br />
          <p style="color: orange; font-size: 10pt;">
            ${{ instrumento.precioEnvio }}
          </p>
        </ng-template>
        <button class="btn-outline-primary">
          Agregar al Carrito
        </button>
      </div>
    </div>
  </div>
</div>

// TrabajoPractico7/TP7Labo4/front/src/views/Detalle.vue
<template>
  <div>
    <b-container>
   <b-row> 
       <b-col lg="7" class="izquierda">
       <p><img
            class="imagen" :src="'http://localhost:9001/images/' + instrumentoEncontrado.imagen"/></p>
       <p class="descripcion">Descripcion:<br>
       {{instrumentoEncontrado.descripcion}}</p>
    </b-col>
    <b-col lg="5" class="derecha">
      <p class="vendidos">{{instrumentoEncontrado.cantidadVendida}} vendidos</p>
       <p class="instrumento">{{instrumentoEncontrado.instrumento}}</p>  
       <p class="precio">${{instrumentoEncontrado.precio}}</p>
       <p>Marca:{{instrumentoEncontrado.marca}}<br>
          Modelo:{{instrumentoEncontrado.modelo}}
       </p>
        <p>Costo envío:<br><span class="envio"
                  v-if="instrumentoEncontrado.costoEnvio == 'G' || instrumentoEncontrado.costoEnvio == 0"
                  style="color:green"
                >
                  <img src="/images/camion.png" />
                  Envio gratis a todo el país
                </span>
                <span v-else style="color:orange" class="envio">
                  Costo de envío al interior de Argentina: $
                  {{ instrumentoEncontrado.costoEnvio }}
                </span></p>
         <p><b-button class="boton">Agregar al carrito</b-button></p>
    </b-col>
    </b-row>
    </b-container>
  </div>
</template>

<script>
export default {
  name: "Detalle",
  components: {},
  mounted() {
    this.getInstrumentoXId();
  },
  data() {
    return {
      instrumentoEncontrado: []
    };
  },
  methods: {
      
    async getInstrumentoXId() {
     const parametroId = this.$route.params.id;   
     this.axios.get('http://localhost:9001/instrumento/'+parametroId)
    
     .then(res =>{
         console.log(res);
         this.instrumentoEncontrado = res.data;
     })
     .catch(e =>{
         console.log(e);
          console.log(parametroId);
     })
    }
  }
};
</script>
<style>

.descripcion {
  text-align: left;
  font-size: 12pt;
  font-family: Helvetica;
  margin-top: 30px;
}
.imagen {
  width: 50%;
  align-content: center;

}

.izquierda {
  
  border-right: 1px inset lightgray;
}
.derecha {

  
  border-right: 2px inset lightgray;
  text-align: left;
}
.vendidos {
  margin-top: 20px;
  font-size: 13px;
  font-family: Helvetica;
 
}
.instrumento{
font-weight: bold;
font-family: Helvetica;
font-size: 20px;


  
}

.envio{
   margin-top: 300px; 
   font-family: Helvetica;
}

.precio{
  font-size: 40px; 
  
}
.boton{
    background-color: white;
    color: blue;
    margin-top: 90px;
 
}
</style>
