// TrabajoPracticoSpring5/Tp5Laboratorio/FrontEndInstrumentos/src/components/TopBar.jsx
import React, { Fragment } from "react";
import Navbar from "react-bootstrap/Navbar";
import Nav from "react-bootstrap/Nav";

const TopBar = () => {
  return (
    <Fragment>
      <Navbar bg="dark" variant="dark">
        <Navbar.Brand>BIENVENIDO</Navbar.Brand>
        <Nav className="mr-auto">
          <Nav.Link href="/home">Home</Nav.Link>
          <Nav.Link href="/where">Donde estamos</Nav.Link>
          <Nav.Link href="/productos">Productos</Nav.Link>
          <Nav.Link href="/formulario">Formulario</Nav.Link>
        </Nav>
      </Navbar>
    </Fragment>
  );
};

export default TopBar;

// TrabajoPractico6/TpVueJson/src/components/TopBar.vue
<template>
 <div>
  <b-navbar type="dark" variant="dark">
    <b-navbar-nav>
      <b-nav-item href="/">Home</b-nav-item>
      <b-nav-item href="/Ubicacion">Dónde estamos</b-nav-item>
      <b-nav-item href="/grid">Productos</b-nav-item>
    </b-navbar-nav>
  </b-navbar>
</div>

</template>

<script>
export default {};
</script>

<style lang=""></style>
